name-template: '$RESOLVED_VERSION 🧪'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'fix bug'
  - title: '📦 Dependencies'
    label: 'dependencies'
  - title: ⚠️ Changes
    labels:
      - deprecated
  - title: 📄 Documentation
    labels:
      - docs
      - documentation
autolabeler:
  - label: 'chore'
    files:
      - '*.md'
    branch:
      - '/document{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/IVYPORTAL-[0-9]{1,4}/'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes ne

  $CHANGES