pipeline {
  agent any
  
  options {
    buildDiscarder(logRotator(numToKeepStr: '60', artifactNumToKeepStr: '5'))
  }
  
  triggers {
    pollSCM 'H/15 * * * *'
  }

  tools { 
      maven 'default' 
      jdk 'jdk11' 
  }

  stages {
    stage('build') {
      steps {
        script {
          def projectName = 'PortalStyle'
          def ivyBuildPluginVersion = '8.0.0'
          def ivyEngineVersion = '9.1.0'
          def portalApplicationName = 'Portal'
          def ivyEngineFolder = 'D:/tools/ivy-server/trunk'
          bat "mvn clean install -f AxonIvyPortal/${projectName}/pom.xml"
          bat "mvn com.axonivy.ivy.ci:project-build-plugin:${ivyBuildPluginVersion}:deploy-to-engine -f AxonIvyPortal/PortalStyle/pom.xml -Divy.deploy.engine.app=${portalApplicationName} -Divy.deploy.engine.dir=${ivyEngineFolder} -Divy.engine.version=${ivyEngineVersion}"
        }
      }
    }
  }
}


