version: '3.7'
services:
  ivy:
    image: axonivy/axonivy-engine:nightly
    container_name: ivy-performance-master
    ports:
     - 9000:8080
    volumes:
     - ./configuration/applications/Portal:/ivy/configuration/applications/Portal
     - ./configuration/ivy.yaml:/ivy/configuration/ivy.yaml
     - ./configuration/licence-11.lic:/ivy/configuration/licence-11.lic
     - ./configuration/jvm.options:/ivy/configuration/jvm.options
     - ./configuration/elasticsearch/jvm.options:/ivy/configuration/elasticsearch/jvm.options
     - ./applications:/ivy/applications
     - ./data:/ivy/data
     - ./work:/ivy/work
     - ./logs:/ivy/logs
    networks:
     - postgres_network
networks:
  postgres_network:
    external: true

