package ch.ivy.addon.portalkit.enums;

public enum AdditionalProperty {

  CUSTOMIZATION_ADDITIONAL_CASE_DETAILS_PAGE,
  CASE_BUSINESS_ENTITY_PROPERTY,
  HIDE,
  ORIGINAL_ADHOC_EXPRESS_TASK,
  ADHOC_EXPRESS_TASK,
  FIRST_TIME_OPEN_ORIGINAL_ADHOC_TASK,
  PORTAL_GROUP_CHAT_INFO;
}
