package ch.ivy.addon.portalkit.enums;

public enum BreadCrumbKind {
  HOME, PROCESS, TASK, TASK_DETAIL, CASE_DETAIL, CASE, TECHNICAL_CASE, RELATED_TASK, STATISTICS, EXPRESS, USER_PROFILE, EXPRESS_BUSINESS,
  ABSENCES_MANAGEMENT, EDIT_PRIVATE_DASHBOARD, EDIT_PUBLIC_DASHBOARD, REORDER_MY_DASHBOARD, REORDER_PUBLIC_DASHBOARD, EDIT_DASHBOARD_DETAILS,
  PROCESS_VIEWER;
}
