package ch.ivy.addon.portalkit.enums;

public enum BreadCrumbKind {
  HOME, PROCESS, TASK, TASK_DETAIL, CASE_DETAIL, CASE, TECHNICAL_CASE, RELATED_TASK, DASHBOARD, EXPRESS, USER_PROFILE, EXPRESS_BUSINESS;
}
