package ch.ivy.addon.portalkit.enums;

public enum BreadCrumbKind {
  HOME, PROCESS, TASK, TASK_DETAIL, CASE_DETAIL, CASE, TECHNICAL_CASE, RELATED_TASK, STATISTICS, EXPRESS, USER_PROFILE, EXPRESS_BUSINESS,
  ABSENCES_MANAGEMENT, DASHBOARD_CONFIGURATION, EDIT_DASHBOARD_DETAILS, PROCESS_VIEWER, PORTAL_MANAGEMENT;
}
