package com.axonivy.portal.components.enums;

public enum GlobalVariable {

  ENABLE_SCRIPT_CHECKING_FOR_UPLOADED_DOCUMENT,
  ENABLE_VIRUS_SCANNER_FOR_UPLOADED_DOCUMENT,
  UPLOAD_DOCUMENT_WHITELIST_EXTENSION;
}
