package ch.ivy.addon.portalkit.service;

import java.util.Arrays;
import java.util.Date;
import java.util.List;

import ch.ivy.addon.portalkit.enums.PortalLibrary;
import ch.ivy.addon.portalkit.persistence.variable.CustomField;
import ch.ivy.addon.portalkit.persistence.variable.IvyVariable;
import ch.ivyteam.ivy.application.IProcessModelVersion;
import ch.ivyteam.ivy.environment.Ivy;
import ch.ivyteam.ivy.workflow.CaseState;
import ch.ivyteam.ivy.workflow.ICase;
import ch.ivyteam.ivy.workflow.query.CaseQuery;
import ch.ivyteam.ivy.workflow.query.CaseQuery.IFilterQuery;

public class DeleteFinishedHiddenCasesService {

  public void deleteFinishedHiddenCases() {
	    Date currentDate = new java.util.Date();
	    Ivy.log().info("***Job for deleting finished hidden system cases started at: " + currentDate + " by user: " + Ivy.session().getSessionUserName());

	    boolean shouldDeleteAllCases = Boolean.parseBoolean(Ivy.var().get(IvyVariable.DELETE_ALL_FINISHED_HIDDEN_CASES));
	    PortalConnectorDetector detector = new PortalConnectorDetector();
	    IProcessModelVersion portalKitPMV = detector.findPortalPMVByLibraryId(Ivy.wf().getApplication(), PortalLibrary.PORTAL_KIT.getValue());
	    CaseQuery caseQuery = CaseQuery.create();
	    List<CaseState> filteredStates = Arrays.asList(CaseState.DONE, CaseState.DESTROYED);
	    CaseQuery stateFieldQuery = CaseQuery.create();
	    IFilterQuery stateFilteredQuery = stateFieldQuery.where();
	    for (CaseState state : filteredStates) {
	    	stateFilteredQuery.or().state().isEqual(state);
	    }
	    caseQuery.where().and(stateFieldQuery);
	    if (!shouldDeleteAllCases) {
	    	//filter only cases generated by Portal
	    	CaseQuery pmvQuery = CaseQuery.create();
	    	pmvQuery.where().processModelId().isEqual(portalKitPMV.getId());
	    	caseQuery.where().and(pmvQuery);
	    }
	    caseQuery.orderBy().caseId().ascending();
	    List<ICase> cases = Ivy.wf().getCaseQueryExecutor().getResults(caseQuery, 0, -1);

	    int numOfDeletedCases = 0;
	    for (int i = cases.size()-1; i >= 0; i--) {
	      ICase iCase = (cases.get(i));
	      if (isHiddenCase(iCase)) {
	        try {
	          Ivy.wf().deleteCompletedCase(iCase);
	          Ivy.log().info("Case was deleted with id: " + iCase.getId());
	          numOfDeletedCases++;
	        } catch (Exception e) {
	          Ivy.log().error("Cannot delete case: " + iCase.getId(), e);
	        }
	      }
	    }

	    currentDate = new java.util.Date();
	    Ivy.log().info("***Job for deleting finished hidden cases (deleted " + numOfDeletedCases + " cases) has ended at: " + currentDate);
  }

  private boolean isHiddenCase(ICase iCase) {
    String hiddenTasksCasesCustomField = Ivy.var().get(IvyVariable.PORTAL_HIDDEN_TASK_CASE_CUSTOM_FIELD);
    boolean isHiddenCase;
    switch (hiddenTasksCasesCustomField.toLowerCase()){
      case CustomField.CUSTOM_VARCHAR_FIELD1: 
        isHiddenCase = iCase.getCustomVarCharField1() != null;
        break;
      case CustomField.CUSTOM_VARCHAR_FIELD2:
    	isHiddenCase = iCase.getCustomVarCharField2() != null;
        break;
      case CustomField.CUSTOM_VARCHAR_FIELD3:
    	isHiddenCase = iCase.getCustomVarCharField3() != null;
        break;
      case CustomField.CUSTOM_VARCHAR_FIELD4:
    	isHiddenCase = iCase.getCustomVarCharField4() != null;
        break;
      case CustomField.CUSTOM_VARCHAR_FIELD5:
    	isHiddenCase = iCase.getCustomVarCharField5() != null;
        break;
      case CustomField.CUSTOM_DECIMAL_FIELD1:
    	isHiddenCase = iCase.getCustomDecimalField1() != null;
        break;
      case CustomField.CUSTOM_DECIMAL_FIELD2:
    	isHiddenCase = iCase.getCustomDecimalField2() != null;
        break;
      case CustomField.CUSTOM_DECIMAL_FIELD3:
    	isHiddenCase = iCase.getCustomDecimalField3() != null;
        break;
      case CustomField.CUSTOM_DECIMAL_FIELD4:
    	isHiddenCase = iCase.getCustomDecimalField4() != null;
        break;
      case CustomField.CUSTOM_DECIMAL_FIELD5:
    	isHiddenCase = iCase.getCustomDecimalField5() != null;
        break;
      case CustomField.CUSTOM_TIMESTAMP_FIELD1:
    	isHiddenCase = iCase.getCustomTimestampField1() != null;
        break;
      case CustomField.CUSTOM_TIMESTAMP_FIELD2:
    	isHiddenCase = iCase.getCustomTimestampField2() != null;
        break;
      case CustomField.CUSTOM_TIMESTAMP_FIELD3:
    	isHiddenCase = iCase.getCustomTimestampField3() != null;
        break; 
      case CustomField.CUSTOM_TIMESTAMP_FIELD4:
    	isHiddenCase = iCase.getCustomTimestampField4() != null;
        break;
      case CustomField.CUSTOM_TIMESTAMP_FIELD5:
    	isHiddenCase = iCase.getCustomTimestampField5() != null;
        break;  
      default:
        isHiddenCase = iCase.getAdditionalProperty("HIDE") != null;
        break;
    }
    return isHiddenCase;
  }
}
