pipeline {

  agent {
    label 'docker'
  }

  options {
    buildDiscarder(logRotator(artifactNumToKeepStr: '50'))
  }

  triggers {
    pollSCM 'H/10 * * * *'
    cron '@midnight'
  }

  stages {    
    stage('build') {
      steps {        
        dir ('Documentation/PortalUserGuide') {
            script {
                docker.image('axonivy/build-container:read-the-docs-1.1').inside {
                    sh "make -C /doc-build html BASEDIR='${env.WORKSPACE}/Documentation/PortalUserGuide'"
                }
            }
            archiveArtifacts 'build/html/**/*'
            recordIssues tools: [sphinxBuild()], unstableTotalAll: 1
        }
      }
    }
  }
}

