version: '3.7'
services:
  ivy:
    image: axonivy/axonivy-engine:nightly
    container_name: ivy-master
    ports:
     - 8000:8080
    volumes:
     - ./applications:/ivy/applications
     - ./data:/ivy/data
     - ./logs:/ivy/logs
     - ./configuration/applications:/ivy/configuration/applications
     - ./configuration/ivy.yaml:/ivy/configuration/ivy.yaml
     - ./configuration/licence-11.lic:/ivy/configuration/licence-11.lic
    networks:
     - postgres_network
networks:
 postgres_network:
   external: true

