package com.axonivy.portal.smart.statistic.dto;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.axonivy.portal.smart.ai.AgentEnums;

/**
 * One filter of a chart, in the narrow vocabulary the agent is allowed to use.
 *
 * Deliberately NOT reusing {@code com.axonivy.portal.enums.dashboard.filter.FilterOperator}:
 * it carries {@code @JsonValue} on {@code getOperator()}, so the JSON schema generated by
 * reflection would advertise {@code IN} while Jackson would expect {@code in}. The nested enums
 * below have no such annotation, which keeps the schema and the parser in agreement.
 *
 * Every field is nullable. The OpenAI provider is configured with {@code responseFormat} but
 * without {@code strictJsonSchema}, so the model may legally omit anything - the mapper's
 * null-tolerance is load-bearing rather than defensive.
 */
public class SmartChartFilterSpec implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * Only the operators the statistic query pipeline actually implements. Anything outside this
   * set is silently dropped by {@code StatisticService.processFilter} - the field-specific
   * {@code generateTaskFilter} / {@code generateCaseFilter} switches return null on an
   * unmatched operator - so narrowing the schema turns a silent no-op into a catchable error.
   */
  public enum OperatorValue {
    IN, NOT_IN, CURRENT_USER, NO_CATEGORY, CONTAINS, NOT_CONTAINS,
    TODAY, YESTERDAY, IS, BEFORE, AFTER, BETWEEN, CURRENT, LAST, NEXT,
    LESS, LESS_OR_EQUAL, GREATER, GREATER_OR_EQUAL;

    @JsonCreator
    public static OperatorValue fromJson(String value) {
      return AgentEnums.parse(OperatorValue.class, value);
    }
  }

  public enum PeriodTypeValue {
    DAY, WEEK, MONTH, YEAR;

    @JsonCreator
    public static PeriodTypeValue fromJson(String value) {
      return AgentEnums.parse(PeriodTypeValue.class, value);
    }
  }

  /**
   * Beware: filter field names are NOT aggregation field names. A task responsible is
   * {@code activator} here but {@code responsibles.name} as an aggregation; a case creator is
   * {@code creator} here but {@code creator.name} as an aggregation.
   */
  private String field;
  private OperatorValue operator;

  /** IN / NOT_IN. */
  private List<String> values;

  /** BETWEEN, formatted as {@code BaseFilter.DATE_FORMAT} ("MM/dd/yyyy HH:mm"). */
  private String from;
  private String to;

  /** LAST / NEXT. */
  private Long periods;

  /** LAST / NEXT / CURRENT. */
  private PeriodTypeValue periodType;

  /** True when {@code field} names a task/case custom field rather than a standard one. */
  private Boolean custom;

  public String getField() {
    return field;
  }

  public void setField(String field) {
    this.field = field;
  }

  public OperatorValue getOperator() {
    return operator;
  }

  public void setOperator(OperatorValue operator) {
    this.operator = operator;
  }

  public List<String> getValues() {
    return values;
  }

  public void setValues(List<String> values) {
    this.values = values;
  }

  public String getFrom() {
    return from;
  }

  public void setFrom(String from) {
    this.from = from;
  }

  public String getTo() {
    return to;
  }

  public void setTo(String to) {
    this.to = to;
  }

  public Long getPeriods() {
    return periods;
  }

  public void setPeriods(Long periods) {
    this.periods = periods;
  }

  public PeriodTypeValue getPeriodType() {
    return periodType;
  }

  public void setPeriodType(PeriodTypeValue periodType) {
    this.periodType = periodType;
  }

  public Boolean getCustom() {
    return custom;
  }

  public void setCustom(Boolean custom) {
    this.custom = custom;
  }
}
