CustomFields:
  Tasks:
    HIDE:
      Label: Hide task custom field
      Description: Set HIDE to this custom field to mark a task as a hidden task on the Portal
      Type: STRING
  Cases:
    HIDE:
      Label: Hide case custom field
      Description: Set HIDE to this custom field to mark a case as a hidden task on the Portal
      Type: STRING
  Starts:
    portalSortIndex:
      Label: Sort index on the Portal dashboard
      Description: The predefined sort index for this startable process on the Portal dashboard
    processImage:
      Label: Process image
      Description: Predefined image location for this start
    isDashboardProcess:
      Label: Portal Custom widget
      Description: Set to 'true' to mark this start can be used as a Custom widget on the Portal dashboard
    portalProcessInfo:
      Label: Custom process information
      Description: Set content (HTML tags are supported) to this custom field to override Process Information Page of a process