Variables:
  Portal:
    # To set the standard homepage which will be redirect to when click on home icon or logo.
    # This setting also affects to the ends page after finished a task.
    Homepage: Dashboard

    # Set to true to start a process/task in IFrame mode.
    EmbedInFrame: true

    # The standard announcement for Portal, it included a general information (e.g. Downtime, Changes, etc.).
    # This message can be seen by all portal users.
    # [file: json]
    Announcement:

    # You can define the standard client statistic via this JSON file.
    # You can configure dashboards to show the statistics to dashboards.
    # [file: json]
    ClientStatistic:

    # A feedback message will be displayed after user finishes or leaves a task.
    DisplayMessageAfterFinishTask: true

    # The option to show logged-in user format.
    # [enum: USERNAME, DISPLAY_NAME, DISPLAY_NAME_USERNAME, USERNAME_DISPLAY_NAME]
    LoggedInUserFormat: DISPLAY_NAME

    # For switch on/off the display of global search.
    ShowGlobalSearch: true
    
    # For switch on/off the display of quick global search.
    ShowQuickGlobalSearch: false
    
    # For switch on/off the display icon in button.
    ShowButtonIcon: true

    # Display the custom end page at the end of each Express process.
    ExpressEndPage: true

    # This setting is using for SecurityMemberDisplayName component.
    # If the SecurityMember is a role, set this setting to true to list out all users of this role.
    # If set to true, icon info is shown beside the role name.
    DisplayUsersOfRole: false

    # The standard sets of filters that Portal used to define the public filters set in the task analysis page.
    # It will be shown as the public filters in the task analysis page.
    # [file: json]
    TaskAnalysisFilters:

    # You can define your custom menu item via this JSON file.
    # It will be included to the left menu.
    # [file: json]
    ThirdPartyApplications:

    # You can define the standard statistic charts via this JSON file.
    # It will be shown as the default charts in the statistic page.
    # [file: json]
    StatisticCharts:
    
    # [file: json]
    PasswordValidation:

    # You can define the own user menu via this JSON file.
    # It will be shown as the your user menu in the user menu settings.
    # [file: json]
    UserMenu:
      # If true, the logout button on top menu will be hidden, otherwise it will be shown.
      HideLogoutMenu: false

      # Set this variable to true to hide the "Change Password" option in the top menu and the "Forgotten Password" option on the login page. If set to false, these options will be shown.
      # [boolean]
      HideChangePasswordMenu: false
      
      # For switch on/off the display of QR code.
      ShowQRCode: false
      
      # Set Base URL for QR code to display
      BaseQRCodeUrl: ''
      # Set URL to download Axon Ivy mobile app on Apple Store.
      AppleStoreURL: 'https://apps.apple.com/us/app/axon-ivy/id6474303078'
      # Set URL to download Axon Ivy mobile app on Google Play.
      GooglePlayURL: 'https://play.google.com/store/apps/details?id=com.axonivy&pli=1'

    # You can configure the look and feel for dashboard according to your needs via this json file.
    # This setting will be taken over for all other dashboard.
    # [file: json]
    Dashboard:
      # Set to true to hide Statistic widget from homepage and application menu.
      HideStatisticWidget: false
      
      # You can customize the name and icon of the main menu entry for Portal dashboards via this JSON file.
      # [file: json]
      MainMenuEntry:      
    

    
    Processes:
      # The standard setting of view mode in the process list.
      # [enum: COMPACT, IMAGE, GRID]
      Mode: IMAGE
      
      # The standard setting of default image that will be displayed in the image process list.
      # [enum:  ARROWRIGHT, BILLING, CHECK, CONTRACTING, DASHBOARD, DASHBOARD2, HELPDESK, HELPDESK2, HR, HR2, INNOVATION, INNOVATION2, INVESTMENT, LOAN, MUGBEGIN, NASASTART, PROCESSMODELING, PROJECTMANAGEMENT, PROJECTMANAGEMENT2, PURCHASING, PURCHASING2, SPORT, WARTUNG, WARTUNG2]
      DefaultImage: DEFAULT

      # The standard external links of Portal.
      # [file: json]
      ExternalLinks:

      # The standard express processes of Portal.
      # [file: json]
      ExpressProcesses:

      # Set to true to disable link to Show Information of process on Processes page (grid mode) and Case Details.
      ShowInformation: true

    Tasks:
      # The standard sets of filters that will be used as the public filters in the task list.
      # [file: json]
      TaskFilters:

      # Task list refresh interval in seconds.
      RefreshInterval: 10000

      # Set to true to disable counting task in task list.
      DisableCount: false

      # The standard sort field of task list
      # [enum: PRIORITY, NAME, ACTIVATOR, ID, CREATION_TIME, EXPIRY_TIME, COMPLETED_ON, STATE, CATEGORY]
      SortField: ID

      # The standard sort field of task list
      # [enum: ASC, DESC]
      SortDirection: DESC

      # For switch behaviours (run the task or access task details) when clicking on a task in task list page, task widget of dashboard and task list in case details page.
      # [enum: ACCESS_TASK_DETAILS, RUN_TASK]
      BehaviourWhenClickingOnLineInTaskList: RUN_TASK
    
    # You can configure the look and feel for task details according to your needs via this json file.
    # This setting will be taken over for all other task details.
    # [file: json]
    TaskDetails:
      # Set to true, the document section in task detail page will be hidden, otherwise it will be shown.
      HideDocument: false

      # For switch on/off the display of the duration time in task details page.
      ShowDurationTime: true

    Cases:
      # The standard sets of filters that will be used as the public filters in the case list.
      # [file: json]
      CaseFilters:

      # Set to true to enable filtering case owner when cases are queried.
      # This setting affects all case queries, e.g. for case list, global search, statistic.
      EnableOwner: false

      # Set to true to disable counting case in case list.
      DisableCount: false

      # The standard sort field of case list
      # [enum: NAME, CREATOR, OWNER, ID, CREATION_TIME, FINISHED_TIME, STATE, ELAPSED_TIME, CATEGORY]
      SortField: ID

      # The standard sort direction of case list
      # [enum: ASC, DESC]
      SortDirection: DESC

      # Set to true to hide case creator in case list, case widget and case details.
      # This setting affects all case queries, e.g. for case list, global search, statistic.
      HideCaseCreator: false

    # You can configure the look and feel for case details according to your needs via this json file.
    # This setting will be taken over for all other case details.
    # [file: json]
    CaseDetails:
      # For switch on/off the display of the duration time in case details page.
      ShowDurationTime: true
  
      # Set to true to deny upload (also delete) document after a case is done.
      HideUploadDocumentForDoneCase: false
  
      # Set to true, the document section in case detail page will be hidden, otherwise it will be shown.
      HideDocument: false

    Chat:
      # Set this property to true to enable group chat function.
      EnableGroup: false

      # Set this property to true to enable private chat function.
      EnablePrivate: false

      # Chat response timeout in seconds, default value is 0, it means no timeout.
      # If chat messages go through reverse proxy Nginx, chat response timeout must be less than Nginx timeout, e.g. less than 60s.
      ResponseTimeout: 0

      # The set number controls the amount of tabs allowed with active chat.
      # If more tabs are opened, the chat will be disabled in inactive tabs.
      # Allowed values between 1-5
      # [enum: 1, 2, 3, 4, 5]
      MaxConnection: 3

      # Endpoint URL for the RESTful service of Portal chatbot
      ChatBotEndpoint: localhost:8018

    Histories:
      # If true, case note does not display any system tasks for non-administrator users.
      HideSystemTasks: true

      # If true, case/task note does not display any system notes for non-administrator users.
      HideSystemNotes: true

      # If true, case note does not display any system tasks for administrator.
      HideSystemTasksForAdministrator: false
  
      # If true, case/task note does not display any system notes for administrator.
      HideSystemNotesForAdministrator: false

      # If true, case history does not display the related case information in the history table.
      HideRelatedCaseInfo: false

    Document:
      # Set to true to enable script checking for uploaded document. Currently this function supports checking for PDF, Excel, Word.
      EnableScriptChecking: false
      
      # Set to true to enable virus scanner for uploaded document. Currently this function is using API VIRUSTOTAL.
      EnableVirusScanner: true

      # Leave value empty if you allow all extensions.
      # If just allow some extensions, list out extensions here, separated by comma. Example: pdf, txt, doc, docx.
      WhitelistExtension: doc, docx, xls, xlsx, xlsm, csv, pdf, ppt, pptx, txt, zip, jpg, jpeg, bmp, png

    DateTimeFormat:
      # Set to true to hide hours and minutes next to date in the datetime format.
      # This setting affects in Tasks, Cases and Statistic results.
      HideTime: false

      # Set to true to hide year in the datetime format.
      # This setting affects in Tasks, Cases and Statistic results.
      HideYear: false

      # Set to true to enable date filtering with time. This setting affects on task list, case list, statistic.
      DateFilterWithTime: false

    # Set this property to true to enable process viewer option in Task/Case actions
    ProcessViewer: true
    
    # Set this property to true to enable write error log to browser console
    ShowErrorLogToConsole: false

    # For switch on/off the display of user/role avatars.
    ShowAvatar: true
    
    # Interval in seconds to do periodic statistic chart scaling requests.
    # If the interval value is less than 10, periodic statistic chart scaling is disabled.
    StatisticChartScalingInterval: 0

    # The set number controls the amount of direct children roles that is shown in Role Management tab.
    # [enum: 10, 50, 100]
    RoleDirectChildrenLimit: 50

    # The set number controls the amount of parent roles that is shown when filtering roles in Role Management tab.
    # [enum: 5, 10, 20]
    RoleParentLimit: 10

    LoginPage:
      # For switch on/off the display of the footer on the Login Page.
      ShowFooter: true

    Theme:
      # Set this property to true to enable the switch theme button
      EnableSwitchThemeModeButton: true
      # The default theme mode of the application
      # [Enum: LIGHT, DARK]
      Mode: LIGHT

    # You can define your custom dashboard templates that used when creating a new dashboard via this JSON file.
    # [file: json]
    DashboardTemplates:

    SearchScope:
      # Defining the fields that the global search will use to find matching tasks beside task Id (this can influence the performance of the search)
      # [Enum: NAME, DESCRIPTION]
      ByTaskFields: NAME,DESCRIPTION

      # Defining the fields that the global search will use to find matching cases beside case Id (this can influence the performance of the search)
      # [Enum: NAME, DESCRIPTION, CUSTOM]
      ByCaseFields: NAME,DESCRIPTION,CUSTOM
    # Defining the types that the global search will search for
    GlobalSearchScopeCategories: PROCESSES,TASKS,CASES

    # Additional menu items for the main menu of Portal. Could be an Ivy process or an external link.
    # [file: json]
    CustomMenuItems:

    # Global footer info that is displayed in bottom right corner can be set in the portal admin settings.
    GlobalFooterInfo: ''

    # Support the translation from English to the other languages or from German to the other languages (German, English, French, Spanish)
    DeepL:
      # DeepL Authentication Key (should end with :fx)
      # [password]
      AuthKey: ''
      # Set this property to true to enable the DeepL translation support
      Enable: false

    # You can define AI assistants here
    # [file: json]
    Assistant:

    # You can define AI Tools
    # [file: json]
    AiTool:

  #URL to the REST service endpoint of Portal AI
  PortalAiUrl: 'http://localhost:8018'

    # You can define the application name via this JSON file.
    # It will be shown with the page title
    ApplicationName: Axon Ivy

  # If set to true, the cron job runs daily (at 6.AM as default) will clean all finished hidden cases in engine.
  # Otherwise, just hidden cases which were generated by Portal will be deleted.
  PortalDeleteAllFinishedHiddenCases: false

  # By default, portal will query only tasks and cases which don't have hide information (store in either additional property or custom field)
  # Set it to false will ingore this feature
  PortalHiddenTaskCaseExcluded: true

  # By default, Portal will redirect to Login Page if login is required and user is unknown.
  # If set to false, redirect to login error page.
  PortalLoginPageDisplay: true

  # @Deprecated(Since 11.2)
  # Cron expression define the time to clean up obsoleted data.
  # Please refer to Axon Ivy CRON job pattern documentation.
  PortalStartTimeCleanObsoletedDataExpression: '0 6 * * *'

  # The delay time of search function at top menu
  PortalSearchDelayInMilliseconds: 500