pipeline {
  agent {
    label 'loc-pc'
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '60', artifactNumToKeepStr: '2'))
  }

  triggers {
    cron '@midnight'
  }

  parameters {
      string(name: 'ivyVersion', defaultValue: 'nightly-10.0', description: 'Ivy version use to replace |version| placeholder of the links which navigate to ivy documentation. e.g.: https://developer.axonivy.com/doc/nightly-10.0/designer-guide/configuration/variables.html')
  }

  stages {
    stage('build') {
      steps {
        script {
          currentBuild.description = "On ${env.NODE_NAME}"
          def version = 'dev'
          docker.withRegistry('', 'docker.io') {
            docker.image('maven:3.6.3-openjdk-17-slim').inside {
              version = getCurrentVersion()
            }
            sh "unzip /mnt/portal02/document-screenshots/portal-document-screenshots-${version}.zip -d Documentation/portal-guide/source/screenshots"
            docker.image('maven:3.6.3-openjdk-17-slim').inside {
              sh "java --version"
              maven cmd: '--version'
              maven cmd: 'clean process-resources -Divy.engine.version=[10.0.1,] -Divy.engine.download.url=https://developer.axonivy.com/permalink/nightly-10.0/axonivy-engine.zip -f Documentation/public-api/pom.xml'
              maven cmd: 'clean generate-resources -f Documentation/pom.xml'
            }
            sh "chmod +x Documentation/portal-guide/substitute.sh && Documentation/portal-guide/substitute.sh ${params.ivyVersion}"
            docker.image('axonivy/build-container:read-the-docs-2').inside {
              sh "make -C /doc-build html BASEDIR='${env.WORKSPACE}/Documentation/portal-guide' VERSION=${version}"
            }

            docker.image('maven:3.6.3-openjdk-17-slim').inside {
              def phase = version.contains('SNAPSHOT') ? 'install' : 'deploy'
              maven cmd: "clean ${phase} -f Documentation/pom.xml"
            }
          }
        }
        archiveArtifacts 'Documentation/*/build/html/**/*, Documentation/*/target/*.zip'
        recordIssues tools: [sphinxBuild()], unstableTotalAll: 1
      }
    }
  }
}

def getCurrentVersion() {
  def cmd = 'mvn help:evaluate -Dexpression=revision -q -DforceStdout -f Documentation/pom.xml'
  def value = sh (script: cmd, returnStdout: true)
  echo "version is $value"
  if (value == 'null object or invalid expression') {
    throw new Exception('could not evaluate maven revision property');
  }
  return value
}