name: Lint Code Base

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/IVYPORTAL-16459-OpenSource ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
