name: Reusable Release Drafter

on:
  workflow_call:

env:
  DRAFTER_NAME: Next Release 🛒
  DRAFTER_TAG: next

permissions:
  contents: write
  pull-requests: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Release Draft Settings
        run: |

          echo $GITHUB_REF_NAME
          echo $DRAFTER_NAME
          echo $DRAFTER_TAG
          echo $github.ref

          echo "DRAFTER_NAME=Next Release $RELEASE_VERSION 🛒" >> $GITHUB_ENV
          if [[ "$GITHUB_REF_NAME" = release/* ]]; then
            RELEASE_VERSION="${GITHUB_REF_NAME#release/}"
            echo "DRAFTER_NAME=Next Release $RELEASE_VERSION 🛒" >> $GITHUB_ENV
            echo "DRAFTER_TAG=next-$RELEASE_VERSION" >> $GITHUB_ENV
            

          fi

      # - uses: release-drafter/release-drafter@v6
      #   with:
      #     name: ${{ env.DRAFTER_NAME }}
      #     tag: ${{ env.DRAFTER_TAG }}
      #     commitish: "refs/heads/release/10.0"
          
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}