name: Internationalization (i18n)
run-name: Update language files

on:
  push:
    branches:
      - feature/IVYPORTAL-19240-Integrate-Portal-Documentation-into-Weblate
    paths:
      - 'Documentation/portal-guide/source/**'
  workflow_dispatch:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: POT Templates
        working-directory: Documentation/portal-guide
        run: |
          # Create filtered copy excluding Japanese folders
          mkdir -p /tmp/filtered-docs
          rsync -av \
            --exclude='source/portal-components-japanese' \
            --exclude='source/portal-developer-guide-japanese' \
            --exclude='source/portal-user-guide-japanese' \
            ./ /tmp/filtered-docs/

          # Run the command on filtered docs
          docker run -v /tmp/filtered-docs:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make gettext BASEDIR=/doc
      - name: Update PO Languages
        working-directory: Documentation/portal-guide
        run: |
          docker run -v /tmp/filtered-docs:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make\
            generatePO BASEDIR=/doc LOCALEDIR=/doc/weblate/locale LANGUAGE=ja
      - name: Locale Diff
        id: locale-diff
        working-directory: Documentation/portal-guide
        run: |
          echo "LOCALE_DIFF<<EOF" >> $GITHUB_ENV
          git --no-pager status -s /tmp/filtered-docs/weblate/locale/* >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create Pull Request
        if: ${{ env.LOCALE_DIFF != '' }}
        working-directory: .
        run: |
          echo "committing changes:\n ${{ env.LOCALE_DIFF }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git checkout -b languages
          git add Documentation/portal-guide/weblate/locale/*
          git commit -m "update PO language files"
          git push -u -f origin languages
          gh pr create --title "Language update :globe_with_meridians:"\
            --body "auto-updates language files"\
            --label "i18n"\
            --base feature/IVYPORTAL-19240-Integrate-Portal-Documentation-into-Weblate
        env:
          GH_TOKEN: ${{ github.token }}