name: Portal Multilingual Documentation
run-name: 📚 Portal Multilingual Documentation
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  discussions: write
  pages: write
on:
  workflow_dispatch:
    inputs:
      ivyVersion:
        description: 'Ivy version use to replace |version| placeholder of the links which navigate to ivy documentation. e.g.: https://developer.axonivy.com/doc/nightly/designer-guide/configuration/variables.html'
        default: 'nightly-12'
        required: true

jobs:
  build-document:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          server-id: 'nexus.axonivy.com'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8

      - name: Get current version
        id: get_version
        run: |
          echo "Build portal document. Use input 'ivyVersion' with default value is 'nightly'" >> $GITHUB_STEP_SUMMARY
          VERSION=$(mvn help:evaluate -Dexpression=revision -q -DforceStdout -f Documentation/pom.xml)
          if [[ "$VERSION" == "null object or invalid expression" ]]; then
            echo "Error: could not evaluate maven revision property"
            # Stops the workflow if the condition is met
            exit 1
          fi
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Version is $VERSION"
      - name: Download artifacts from screenshot workflow
        uses: dawidd6/action-download-artifact@v9
        with:
          workflow: portal-document-screenshot-test.yml
          name: screenshots
          branch: release/12.0
          path: Documentation/portal-guide/source/screenshots

      - name: install zip
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq Documentation/portal-guide/source/screenshots/*.zip -d Documentation/portal-guide/source/screenshots/

      - name: Generate resources
        run: |
          mvn clean process-resources -Divy.engine.version=[12.0.0,] -Divy.engine.download.url=https://developer.axonivy.com/permalink/nightly-12.0/axonivy-engine.zip -f Documentation/public-api/pom.xml
          mvn clean generate-resources -f Documentation/pom.xml
      - name: Run substitute
        shell: bash
        run: chmod +x Documentation/portal-guide/substitute.sh && Documentation/portal-guide/substitute.sh ${{ inputs.ivyVersion }}

      - name: Build English Documentation HTML
        id: build-en-html
        run: |
          docker run -u root:root --rm -v ${{ github.workspace }}:/workspace -w /workspace/Documentation/portal-guide \
            axonivy/build-container:read-the-docs-2 make -C /doc-build html BASEDIR='/workspace/Documentation/portal-guide' \
            VERSION=${{ steps.get_version.outputs.version }} VERSION_SWITCHER=true 2> sphinx-warnings-en.log
          WARNINGS=$(grep -c "WARNING" sphinx-warnings-en.log || echo 0)
          echo "Found $WARNINGS warnings in English documentation."
          if [ "$WARNINGS" -ge 1 ]; then
            echo "English documentation build has warnings. Adding to summary..."
            echo "### English Documentation Build Warnings" >> $GITHUB_STEP_SUMMARY
            echo "Found $WARNINGS warnings during the documentation build." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### Warning Details" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat sphinx-warnings-en.log >> $GITHUB_STEP_SUMMARY
            cat sphinx-warnings-en.log
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          sudo mkdir -p Documentation/portal-guide/build/doc/en
          sudo mv Documentation/portal-guide/build/html/* Documentation/portal-guide/build/doc/en/

      - name: Build Japanese Documentation HTML
        id: build-ja-html
        run: |
          docker run -u root:root --rm -v ${{ github.workspace }}:/workspace -w /workspace/Documentation/portal-guide \
            axonivy/build-container:read-the-docs-2 make -C /doc-build html BASEDIR='/workspace/Documentation/portal-guide' \
            LOCALEDIR=/workspace/Documentation/portal-guide/weblate/locale SPHINXOPTS="-D language='ja'" \
            VERSION=${{ steps.get_version.outputs.version }} VERSION_SWITCHER=true 2> sphinx-warnings-ja.log
          WARNINGS=$(grep -c "WARNING" sphinx-warnings-ja.log || echo 0)
          echo "Found $WARNINGS warnings in Japanese documentation."
          if [ "$WARNINGS" -ge 1 ]; then
            echo "Japanese documentation build has warnings. Adding to summary..."
            echo "### Japanese Documentation Build Warnings" >> $GITHUB_STEP_SUMMARY
            echo "Found $WARNINGS warnings during the documentation build." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "#### Warning Details" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat sphinx-warnings-ja.log >> $GITHUB_STEP_SUMMARY
            cat sphinx-warnings-ja.log
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
          sudo mkdir -p Documentation/portal-guide/build/doc/ja
          sudo mv Documentation/portal-guide/build/html/* Documentation/portal-guide/build/doc/ja/

      - name: Install or deploy document
        run: |
          sudo chmod -R a+rwx Documentation/
          if [[ "${{ steps.get_version.outputs.version }}" == *SNAPSHOT* ]]; then
            PHASE="install"
          else
            PHASE="deploy"
          fi
          echo "Running 'clean $PHASE' for version ${{ steps.get_version.outputs.version }}"
          mvn clean $PHASE -f Documentation/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.NEXUS_AXONIVY_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEXUS_AXONIVY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation-multilingual-${{ steps.get_version.outputs.version }}
          path: |
            Documentation/portal-guide/target/*.zip