name: Portal Documentation Weblate
run-name: 🌐 Update Portal Documentation files in Weblate
permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Generate POT Templates
        working-directory: Documentation/portal-guide
        run: |
          docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make gettext BASEDIR=/doc

      - name: Update PO Languages files
        working-directory: Documentation/portal-guide
        run: |
          docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2 make\
            generatePO BASEDIR=/doc LOCALEDIR=/doc/weblate/locale LANGUAGE=ja O="--line-width -1"

      - name: Check Locale Diff
        id: locale-diff
        working-directory: Documentation/portal-guide
        run: |
          echo "LOCALE_DIFF<<EOF" >> $GITHUB_ENV
          git --no-pager status -s weblate/locale/* >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Revert PO header
        if: ${{ env.LOCALE_DIFF != '' }}
        run: |
          for po in locale/*/LC_MESSAGES/*.po; do
            if git show HEAD:"$po" > /dev/null 2>&1; then
              old_header_end=$(git show HEAD:"$po" | grep -n '^$' | head -1 | cut -d: -f1)
              new_header_end=$(grep -n '^$' "$po" | head -1 | cut -d: -f1)
              git show HEAD:"$po" | head -$((old_header_end - 1)) > /tmp/old_header
              tail -n +$new_header_end "$po" > /tmp/body
              cat /tmp/old_header /tmp/body > "$po"
            fi
            sed -i -z 's/\n$//' "$po"  # remove empty line at end of file if exists
          done

      - name: Create branch name
        working-directory: .
        run: |
          NEW_BRANCH="weblate/update-language-files-$(date +%Y%m%d-%H%M%S)"
          echo "WEBLATE_BRANCH=$NEW_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        if: ${{ env.LOCALE_DIFF != '' }}
        working-directory: .
        run: |
          echo "committing changes:\n ${{ env.LOCALE_DIFF }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git checkout -b ${{ env.WEBLATE_BRANCH }}
          git add Documentation/portal-guide/weblate/locale/*
          git commit -m "update PO language files"
          git push -u -f origin ${{ env.WEBLATE_BRANCH }}
          gh pr create --title ":globe_with_meridians: Update PO files for weblate"\
            --body "Update PO files"\
            --label "i18n,skip-changelog"\
            --base master

        env:
          GH_TOKEN: ${{ github.token }}