name: Publish Release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/publish-release.yml@v4
    # The 'publish_release' input parameter is used to control whether the release should be published automatically.
    # Uncomment and set to 'false' if you want to prevent the release from being published immediately.
    # with:
    #   publish_release: false
