name: Publish Release Drafter

on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        type: string

env:
  COMMITISH: master

jobs:

  publish_release_drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Release Draft Settings
        run: |
          VERSION_NUMBER=$(echo "${{inputs.tag}}" | sed -E 's/^([0-9]+\.[0-9]+)\..*/\1/')

          # Check if the branch for this version exists and set COMMITISH
          if [[ $(git branch -r | grep "origin/release/$VERSION_NUMBER") ]]; then
            echo "COMMITISH=release/$VERSION_NUMBER" >> $GITHUB_ENV
          else
            echo "COMMITISH=master" >> $GITHUB_ENV
          fi
      - uses: axonivy-market/github-workflows/.github/workflows/publish-release-drafter.yml@v5
        with:
          tag: ${{ inputs.tag }}
          commitish: ${{ env.COMMITISH }}
