name: Release Drafter
run-name: 🚀 Release Drafter
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  discussions: write
  pages: write
on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to draft release for'
        required: true
        default: 'master'
        type: string

jobs:
  release_drafter:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.ref_name == 'master' || startsWith(github.ref_name, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yml
          commitish: ${{ inputs.branch || github.ref_name }}
          name: Next release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output in a later step
      - name: Check the list of PRs
        run: |
          echo "The generated release body is:"
          echo "${{ steps.release_drafter.outputs.body }}"