name: Super-Linter

on:
  push:
    branches:
      - feature/IVYPORTAL-16678-SPIKE-Setup-Linter
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions: 
        contents: read
        packages: read
        statuses: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Report Directory
        run: mkdir -p /tmp/lint-results

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.2.1
        continue-on-error: true
        id: linter
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          LOG_LEVEL: DEBUG  # Changed to DEBUG for more detailed output
          REPORT_OUTPUT: true
          LOG_FILE: true
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: json

      - name: Process Linter Results
        if: always()
        run: |
          mkdir -p /tmp/lint-results
          if [ -f "/tmp/lint/linter.log" ]; then
            cp /tmp/lint/linter.log /tmp/lint-results/
          else
            echo "No linter.log found in /tmp/lint/"
            ls -la /tmp/lint/
          fi
          
          # Create a summary of results
          echo "### Super-Linter Results" > /tmp/lint-results/summary.md
          echo "" >> /tmp/lint-results/summary.md
          echo "| Language | Status |" >> /tmp/lint-results/summary.md
          echo "|----------|--------|" >> /tmp/lint-results/summary.md
          
          if [ -f "/tmp/lint/linter.log" ]; then
            # Extract results for each linter
            grep -E ".*Linter:.*status:" /tmp/lint/linter.log | while read -r line; do
              linter=$(echo "$line" | grep -o "Linter:[^ ]*" | cut -d: -f2)
              status=$(echo "$line" | grep -o "status:[^ ]*" | cut -d: -f2)
              echo "| $linter | $status |" >> /tmp/lint-results/summary.md
            done
          fi
        
      - name: Upload Linter Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linter-report
          path: /tmp/lint-results/
          retention-days: 1

      - name: Set Job Status
        if: always()
        run: |
          if [ -f "/tmp/lint/linter.log" ] && grep -q "ERROR:" "/tmp/lint/linter.log"; then
            echo "Linting errors found"
            exit 1
          fi

  summary:
    name: Generate Summary
    needs: lint
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download Linter Report
        uses: actions/download-artifact@v4
        with:
          name: linter-report
          path: ./linter-report
          
      - name: Generate Summary
        run: |
          if [ -f "./linter-report/summary.md" ]; then
            cat ./linter-report/summary.md > $GITHUB_STEP_SUMMARY
          else
            echo "### No Linter Results Available" > $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f "./linter-report/linter.log" ]; then
            echo "### Detailed Errors" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            grep -E "ERROR:|WARNING:" ./linter-report/linter.log >> $GITHUB_STEP_SUMMARY || true
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi