name: Super-Linter

on:
  push:
    branches:
      - feature/IVYPORTAL-16678-SPIKE-Setup-Linter
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions: 
        contents: read
        packages: read
        statuses: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Report Directory
        run: mkdir -p /tmp/lint-results

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.2.1
        continue-on-error: true
        id: linter
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true  # Validate the entire codebase
          # Enable specific linters
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_YAML: true
          VALIDATE_XML: true
          VALIDATE_CSS: true
          # Debug settings
          LOG_LEVEL: VERBOSE  # Changed to VERBOSE for more details
          LOG_FILE: true
          REPORT_OUTPUT: true
          CREATE_LOG_FILE: true
          OUTPUT_FOLDER: /github/workspace/super-linter-reports  # Changed output location
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: text

      - name: Debug Linter Output
        if: always()
        run: |
          echo "=== Checking for linter output files ==="
          find /github/workspace -name "*lint*.log" -o -name "super-linter.log" || true
          find /tmp -name "*lint*.log" -o -name "super-linter.log" 2>/dev/null || true
          
          echo "=== Contents of workspace ==="
          ls -la /github/workspace || true
          
          echo "=== Contents of super-linter-reports ==="
          ls -la /github/workspace/super-linter-reports || true

      - name: Process Linter Results
        if: always()
        run: |
          mkdir -p /tmp/lint-results
          
          # Try to find linter logs in multiple locations
          for location in "/github/workspace/super-linter-reports" "/tmp" "/github/workspace"; do
            echo "Searching in $location"
            if [ -d "$location" ]; then
              find "$location" -type f -name "*lint*.log" -o -name "super-linter.log" 2>/dev/null | while read -r file; do
                echo "Found log file: $file"
                cat "$file" > /tmp/lint-results/linter.log
              done
            fi
          done
          
          # Create summary even if no logs found
          echo "### Super-Linter Results" > /tmp/lint-results/summary.md
          echo "" >> /tmp/lint-results/summary.md
          echo "| Language | Status | Details |" >> /tmp/lint-results/summary.md
          echo "|----------|--------|----------|" >> /tmp/lint-results/summary.md
          
          if [ -f "/tmp/lint-results/linter.log" ]; then
            while IFS= read -r line; do
              if echo "$line" | grep -q ".*[Ll]inter:.*status:.*"; then
                echo "Processing line: $line"
                LINTER=$(echo "$line" | grep -o "[Ll]inter:[^ ]*" | cut -d: -f2)
                STATUS=$(echo "$line" | grep -o "status:[^ ]*" | cut -d: -f2)
                echo "| $LINTER | $STATUS | - |" >> /tmp/lint-results/summary.md
              fi
            done < "/tmp/lint-results/linter.log"
          else
            echo "| No logs found | - | Check debug output |" >> /tmp/lint-results/summary.md
          fi

      - name: Upload Linter Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: linter-report
          path: |
            /tmp/lint-results/linter.log
            /tmp/lint-results/summary.md
          retention-days: 1

      - name: Generate Summary
        if: always()
        run: |
          if [ -f "/tmp/lint-results/summary.md" ]; then
            cat /tmp/lint-results/summary.md > $GITHUB_STEP_SUMMARY
            if [ -f "/tmp/lint-results/linter.log" ]; then
              echo "" >> $GITHUB_STEP_SUMMARY
              echo "### Detailed Errors" >> $GITHUB_STEP_SUMMARY
              echo '```' >> $GITHUB_STEP_SUMMARY
              grep -E "ERROR:|WARNING:" /tmp/lint-results/linter.log >> $GITHUB_STEP_SUMMARY || true
              echo '```' >> $GITHUB_STEP_SUMMARY
            fi
          else
            echo "### No Linter Results Available" > $GITHUB_STEP_SUMMARY
          fi

      - name: Check Linter Status
        if: always()
        run: |
          if [ -f "./linter-report/linter.log" ] && grep -E "ERROR" ./linter-report/linter.log > /dev/null; then
            exit 1
          fi
