name: Commit Weblate Translations

on:
  push:
  workflow_dispatch:

jobs:
  commit-translations:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Check and commit Weblate changes (Docker)
      run: |
        COMPONENT="portal/portal-cms"
        echo "Checking uncommitted changes in $COMPONENT..."

        # Run Weblate CLI in Docker
        docker run --rm \
          -v ~/.config/weblate:/root/.config/weblate \
          -e WEBLATE_API_TOKEN=${{ secrets.WEBLATE_API_TOKEN }} \
          weblate/wlc show "$COMPONENT" --format json

        # Check if there are uncommitted changes
        CHANGES=$(docker run --rm \
          -v ~/.config/weblate:/root/.config/weblate \
          -e WEBLATE_API_TOKEN=${{ secrets.WEBLATE_API_TOKEN }} \
          weblate/wlc show "$COMPONENT" --format json | jq -r '.statistics.uncommitted')

        if [ "$CHANGES" != "0" ]; then
          echo "Found $CHANGES uncommitted change(s), committing..."
          docker run --rm \
            -v ~/.config/weblate:/root/.config/weblate \
            -e WEBLATE_API_TOKEN=${{ secrets.WEBLATE_API_TOKEN }} \
            weblate/wlc commit "$COMPONENT"
          echo "✅ Commit triggered."
        else
          echo "No changes to commit."
        fi
