name: YAML to PO Template Converter
on:
  push:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch containing YAML files to convert'
        required: false
        default: 'portal-cms'
      yaml_path:
        description: 'Path to YAML translations directory'
        required: false
        default: 'portal/AxonIvyPortal/portal/cms'
      output_path:
        description: 'Path where PO files will be saved'
        required: false
        default: 'po-templates'
      file_pattern:
        description: 'Pattern for YAML files to convert (e.g., "cms-*.yml" or "*.yaml")'
        required: false
        default: 'cms-*.yml'

jobs:
  convert-yaml-to-po:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.source_branch || 'portal-cms' }}
        
    - name: Install yaml2po
      run: |
        set -euo pipefail
        sudo apt update
        sudo apt install -y translate-toolkit
    
    - name: Prepare output directory
      run: |
        set -euo pipefail
        mkdir -p ${{ github.event.inputs.output_path || 'po-templates' }}
        
    - name: Convert YAML files to PO
      run: |
        set -euo pipefail

        echo "Looking for files matching: ${{ github.event.inputs.file_pattern || 'cms-*.yml' }}"

        matched_files=$(find ${{ github.event.inputs.yaml_path || './AxonIvyPortal/portal/cms' }} -name "${{ github.event.inputs.file_pattern || 'cms-*.yml' }}" -type f)

        if [ -z "$matched_files" ]; then
          echo "Error: No files found matching the pattern ${{ github.event.inputs.file_pattern || 'cms-*.yml' }}"
          exit 1
        fi

        for yaml_path in $matched_files; do
          yaml_file=$(basename "$yaml_path")
          echo "Converting $yaml_file to PO template..."

          if [[ "$yaml_file" == *.yml ]]; then
            filename=$(basename "$yaml_file" .yml)
          else
            filename=$(basename "$yaml_file" .yaml)
          fi

          yaml2po "$yaml_path" "${{ github.event.inputs.output_path || 'po-templates' }}/$filename.pot"

          echo "Created $filename.pot"
        done

        echo "Conversion complete. Created $(find ${{ github.event.inputs.output_path || 'po-templates' }} -name "*.pot" | wc -l) PO template files."
        
    - name: Upload PO templates as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: po-templates
        path: ${{ github.event.inputs.output_path || 'po-templates' }}/*.pot
        retention-days: 7
