name: YAML to PO Template Converter
on:
  push:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Branch containing YAML files to convert'
        required: false
        default: 'portal-cms'
      yaml_path:
        description: 'Path to YAML translations directory'
        required: false
        default: 'portal/AxonIvyPortal/portal/cms'
      output_path:
        description: 'Path where PO files will be saved'
        required: false
        default: 'po-templates'
      file_pattern:
        description: 'Pattern for YAML files to convert (e.g., "cms-*.yml" or "*.yaml")'
        required: false
        default: 'cms-*.yaml'

jobs:
  convert-yaml-to-po:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.source_branch || 'portal-cms' }}
        
    - name: Install yaml2po
      run: |
        set -euo pipefail
        sudo apt update
        sudo apt install -y translate-toolkit
    
    - name: Prepare output directory
      run: |
        set -euo pipefail
        mkdir -p ${{ github.event.inputs.output_path || 'po-templates' }}               
        
    - name: Convert YAML files to PO
      run: |
        set -euo pipefail

        # Convert input into an array
        IFS=',' read -r -a file_list <<< "${{ github.event.inputs.file_list || 'cms-es.yaml' }}"

        # Define the YAML directory and output directory
        yaml_dir="${{ github.event.inputs.yaml_path || './AxonIvyPortal/portal/cms' }}"
        output_dir="${{ github.event.inputs.output_path || 'po-templates' }}"

        # Iterate over the files in the list
        for file in "${file_list[@]}"; do
          yaml_path="$yaml_dir/$file"
          if [ -f "$yaml_path" ]; then
            echo "Converting $yaml_path to PO template..."
            filename=$(basename "$yaml_path" .yaml)
            yaml2po "$yaml_path" "$output_dir/$filename.pot"
            echo "Created $filename.pot"
          else
            echo "Warning: $yaml_path not found!"
          fi
        done

        # Show summary of conversion
        echo "Conversion complete. Created $(find "$output_dir" -name "*.pot" | wc -l) PO template files."  

        
    - name: Upload PO templates as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: po-templates
        path: ${{ github.event.inputs.output_path || 'po-templates' }}/*.pot
        retention-days: 7
